-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 22:53:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wild_dvds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wild_dvds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wild_dvds` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema wild_dvds
-- -----------------------------------------------------
USE `wild_dvds` ;

-- -----------------------------------------------------
-- Table `wild_dvds`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wild_dvds`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zipcode` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wild_dvds`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wild_dvds`.`stock` (
  `movie_id` INT NOT NULL,
  `total_stock` INT NOT NULL,
  `available_stock` INT NOT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wild_dvds`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wild_dvds`.`borrow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `borrow_date` DATE NOT NULL,
  `expected_return_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `stock_movie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `stock_movie_id`),
  INDEX `fk_borrow_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_borrow_stock1_idx` (`stock_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_borrow_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wild_dvds`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrow_stock1`
    FOREIGN KEY (`stock_movie_id`)
    REFERENCES `wild_dvds`.`stock` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
